[SQUASH] AOSP Screen Recording fixes & improvements
Screenrecord: Change save location and make sure dirs exist

https://github.com/ezio84/abc_frameworks_base/commit/bb28be00b1817cbe4b7dd516b60f3b147cad0f75

    - By Surge1223

****************************************************

Screenrec: allow to show a blinking red stop dot

    we could want to stop the recording without expanding the notification
    panel and show sensitive infos.

    Long pressing on the red dot moves it to the opposite side of the
    screen, in case the user want not to cover specific elements on the screen

    Old commit reference: b50c7ca

https://github.com/ezio84/abc_frameworks_base/commit/6092d9ca8b0949d64c1b87d6cd53d66daf002e14

    - By Ezio84

****************************************************

Screenrec: use HEVC H.265 codec, add low quality option, fixes

    h265 should give a smaller file size thanks to the better
    compression/quality ratio

    add also a low quality option that still gives a good recording
    reducing a lot the final file size (useful when sharing the
    screenrecord on data connections)

    better string in the power button option

    code fixes

    TODO: cleanup ScreenRecordDialog code

https://github.com/ezio84/abc_frameworks_base/commit/91c00e8fb70cb17b8658678bf476452f96cd44d1

    - By Ezio84

****************************************************

Screenrecord: fix possible SystemUI FC when stopping

    mMediaRecorder and other instances can be already null if we are tapping
    fast like hell or other deep cases

    11-12 09:12:39.806  1717  1717 E AndroidRuntime: FATAL EXCEPTION: main

    11-12 09:12:39.806  1717  1717 E AndroidRuntime:
    java.lang.RuntimeException: Unable to start service
    com.android.systemui.screenrecord.RecordingService@20e0475 with
    Intent { act=com.android.systemui.screenrecord.STOP
    flg=0x10000000 cmp=com.android.systemui/.screenrecord.RecordingService
    bnds=[28,283][402,451] }: java.lang.NullPointerException:
    Attempt to invoke virtual method 'void
    android.media.MediaRecorder.stop()' on a null object reference

    11-12 09:12:39.806  1717  1717 E AndroidRuntime: Caused by: java.lang.
    NullPointerException: Attempt to invoke virtual method 'void
    android.media.MediaRecorder.stop()' on a null object reference

https://github.com/ezio84/abc_frameworks_base/commit/3e3be6af5253d7ffa4556b6d1cab7d0e1d6a0479

    - By Ezio84

****************************************************

Screenrecord: fix FC when using custom dpi values

    huge thanks to Zenixxx who found the root case

https://github.com/ezio84/abc_frameworks_base/commit/3e9e9ff5a56fdd8d7e084a119d1e3829e6df57a6

    - By Ezio84

****************************************************

Screenrecord: start delayed

    no need to record the dialog animation too

https://github.com/ezio84/abc_frameworks_base/commit/191d0e602657dd036e70bfb4e11e4cb721586525

    - By Ezio84

****************************************************

Screenrecord: exclude dialog from Recents

https://github.com/ezio84/abc_frameworks_base/commit/317edadc89f83514c52bee15fe5d4bfbaadffe42

    - By Ezio84

****************************************************
Screenrecorder: don't show heads up notification

https://github.com/ezio84/abc_frameworks_base/commit/b6f1792364c3091decd30521d4234a9e7eddecd8

    - By Ezio84

****************************************************

Add a new screenrecord icon for statusbar

Credit to Google / Material Design Icons @ http://materialdesignicons.com
for icon http://materialdesignicons.com/icon/video.

https://github.com/ezio84/abc_frameworks_base/commit/0aa2d1f6cdd11e7a20fcf3910228fda1a1e1466f

    - By Mazda--

****************************************************
RecordingService: Use the new statusbar screenrecord icon

https://github.com/ezio84/abc_frameworks_base/commit/c1f8d0807a6e4d7b5de99051d0c9da539b462c24

    - By neobuddy89

****************************************************

Co-authored-by: Surge1223 <surge1223@gmail.com>
Co-authored-by: Alex Cruz <alex@dirtyunicorns.com>
Co-authored-by: Pranav Vashi <neobuddy89@gmail.com>
Change-Id: I27b7b24907100dac861ab3f99f66aaf2241fe5f8